version: "3.7"

services:
  testes_integracao:
    image: postgres
    container_name: testes_integracao
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: fin_api
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - testes_integracao
    depends_on:
      - testes_integracao



volumes:
  pgdata:
    driver: local